/*
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *   node scripts/import-puzzles.mjs
 *
 * Source:
 *   Lichess Chess Puzzle Database
 *
 * Every puzzle in this file was validated with chess.js
 * before being written.
 *
 * Do not manually edit puzzle entries here.
 */

export type PuzzleDifficulty =
  | "easy"
  | "medium"
  | "hard";

export type Puzzle = {
  id: string;

  /*
   * Position BEFORE the opponent's
   * setup move.
   */
  fen: string;

  /*
   * Lichess puzzle format:
   *
   * moves[0] = opponent/setup move
   * moves[1] = solver move
   * moves[2] = opponent response
   * moves[3] = solver move
   * ...
   *
   * Moves use UCI notation.
   *
   * Promotion example:
   * a7a8q
   */
  moves: string[];

  rating: number;
  ratingDeviation: number;

  popularity: number;
  nbPlays: number;

  themes: string[];

  gameUrl: string;

  difficulty:
    PuzzleDifficulty;

  /*
   * Number of moves made by the solver,
   * excluding opponent responses.
   */
  solutionLength: number;
};

export const puzzles: Puzzle[] =
[
  {
    "id": "TkTIG",
    "fen": "r5k1/1b4p1/pp1p2p1/4r1Pn/P5Q1/2P1pPP1/1P1qN1KN/3RR3 w - - 3 29",
    "moves": [
      "d1d2",
      "e3d2",
      "e1d1",
      "e5e2"
    ],
    "rating": 1046,
    "ratingDeviation": 78,
    "popularity": 100,
    "nbPlays": 566,
    "themes": [
      "advancedPawn",
      "advantage",
      "capturingDefender",
      "discoveredAttack",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/QWg3BKnY#57",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXsw7",
    "fen": "5rk1/4pp1p/rq4p1/1NpP4/2PbP3/pP4PP/Q4P2/3R1BK1 b - - 5 29",
    "moves": [
      "f7f5",
      "b5d4",
      "c5d4",
      "c4c5"
    ],
    "rating": 1486,
    "ratingDeviation": 75,
    "popularity": 92,
    "nbPlays": 1769,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/lITFGleD/black#58",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxwAS",
    "fen": "3r4/4rpk1/bq3bpp/p2Q4/P2N4/1B6/1PP3PP/2KR3R w - - 3 26",
    "moves": [
      "d5c6",
      "f6d4",
      "c6b6",
      "d4b6",
      "d1d8",
      "b6d8"
    ],
    "rating": 1703,
    "ratingDeviation": 76,
    "popularity": 93,
    "nbPlays": 1576,
    "themes": [
      "advantage",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/ZfylvMaK#51",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "XxuPE",
    "fen": "3r4/4R3/p7/3N4/kPP3r1/2K5/P3p3/8 b - - 1 45",
    "moves": [
      "d8c8",
      "d5b6",
      "a4a3",
      "b6c8"
    ],
    "rating": 741,
    "ratingDeviation": 98,
    "popularity": 94,
    "nbPlays": 643,
    "themes": [
      "advantage",
      "endgame",
      "fork",
      "master",
      "short"
    ],
    "gameUrl": "https://lichess.org/1oihs42t/black#90",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkSlj",
    "fen": "8/1Np2ppk/4p2p/1n2P3/QPq1PP2/6P1/3R3P/3K4 w - - 5 36",
    "moves": [
      "a4c2",
      "c4f1"
    ],
    "rating": 1162,
    "ratingDeviation": 95,
    "popularity": 95,
    "nbPlays": 1824,
    "themes": [
      "endgame",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/0ABrXYUx#71",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "XxuvY",
    "fen": "5rk1/5pp1/R6p/8/8/4P2P/Prp2PK1/2R5 w - - 0 28",
    "moves": [
      "a2a4",
      "f8c8",
      "a6d6",
      "b2b1",
      "d6d8",
      "c8d8"
    ],
    "rating": 1640,
    "ratingDeviation": 75,
    "popularity": 87,
    "nbPlays": 383,
    "themes": [
      "advantage",
      "endgame",
      "long",
      "quietMove",
      "rookEndgame"
    ],
    "gameUrl": "https://lichess.org/knMJCxFb#55",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXrk1",
    "fen": "8/6p1/3k2p1/6N1/1pKP4/2b4P/8/8 b - - 3 42",
    "moves": [
      "c3d2",
      "g5e4",
      "d6d7",
      "e4d2"
    ],
    "rating": 961,
    "ratingDeviation": 76,
    "popularity": 100,
    "nbPlays": 117,
    "themes": [
      "crushing",
      "endgame",
      "fork",
      "short"
    ],
    "gameUrl": "https://lichess.org/EUinVxcS/black#84",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkSWQ",
    "fen": "2R1b1k1/5qpp/5b2/2B1r3/8/1Q5P/P5P1/1R4K1 b - - 2 32",
    "moves": [
      "e5c5",
      "c8e8"
    ],
    "rating": 1218,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 761,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove",
      "pin"
    ],
    "gameUrl": "https://lichess.org/d15WgKmH/black#64",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "TkTno",
    "fen": "r3kb1r/1p3ppp/1qp5/p1n1n3/4P1b1/1BN2N2/PPPBQ1PP/2KR3R w kq - 0 13",
    "moves": [
      "f3e5",
      "c5b3",
      "c2b3",
      "g4e2"
    ],
    "rating": 1865,
    "ratingDeviation": 78,
    "popularity": 92,
    "nbPlays": 437,
    "themes": [
      "advantage",
      "master",
      "middlegame",
      "queensideAttack",
      "short"
    ],
    "gameUrl": "https://lichess.org/hBX7s3gj#25",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXtnL",
    "fen": "rn2r1k1/pp3p1p/6p1/7K/5q2/2NQbN1P/PP4P1/R4B1R w - - 0 18",
    "moves": [
      "d3g6",
      "h7g6"
    ],
    "rating": 757,
    "ratingDeviation": 76,
    "popularity": 100,
    "nbPlays": 136,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/UCkBVE0J#35",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkS5h",
    "fen": "8/4K3/8/7p/5NkP/6P1/8/3b4 w - - 8 66",
    "moves": [
      "f4g6",
      "g4g3",
      "e7d6",
      "d1c2",
      "g6e7",
      "g3h4"
    ],
    "rating": 1177,
    "ratingDeviation": 77,
    "popularity": 97,
    "nbPlays": 8688,
    "themes": [
      "crushing",
      "endgame",
      "long"
    ],
    "gameUrl": "https://lichess.org/6EWlleXa#131",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "WXqZb",
    "fen": "2r5/p3p1kp/1p1pPp2/4qPp1/7r/2P2QR1/PP4P1/5RK1 b - - 0 31",
    "moves": [
      "h4f4",
      "f3f4",
      "e5f4",
      "f1f4"
    ],
    "rating": 1687,
    "ratingDeviation": 75,
    "popularity": 94,
    "nbPlays": 2636,
    "themes": [
      "crushing",
      "endgame",
      "master",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/SeTsrQdC/black#62",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXq0v",
    "fen": "8/8/6R1/3k1p1p/4p1nP/4P1N1/2r3P1/6K1 w - - 1 50",
    "moves": [
      "g3f5",
      "c2c1"
    ],
    "rating": 847,
    "ratingDeviation": 78,
    "popularity": 85,
    "nbPlays": 210,
    "themes": [
      "endgame",
      "master",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/kAcc4dPw#99",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "XxuMz",
    "fen": "1r2kQr1/p3P2p/n2B2p1/1p2N1P1/2q5/7P/PP3P2/R5K1 b - - 3 31",
    "moves": [
      "g8f8",
      "e7f8q"
    ],
    "rating": 1352,
    "ratingDeviation": 81,
    "popularity": 92,
    "nbPlays": 1408,
    "themes": [
      "advancedPawn",
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove",
      "promotion"
    ],
    "gameUrl": "https://lichess.org/y12V9HQr/black#62",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "WXrnI",
    "fen": "8/1k6/p1p1p1p1/PpP1P1P1/1P2QK2/8/5q2/8 w - - 8 67",
    "moves": [
      "f4g4",
      "f2f5",
      "e4f5",
      "e6f5"
    ],
    "rating": 1622,
    "ratingDeviation": 77,
    "popularity": 87,
    "nbPlays": 1361,
    "themes": [
      "crushing",
      "endgame",
      "master",
      "queenEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/xzdqvny6#133",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkSNz",
    "fen": "r1b1kbnr/1ppp1ppp/p1n5/4p1q1/2B1P3/5Q2/PPPP1PPP/RNB1K2R b KQkq - 1 5",
    "moves": [
      "c6d4",
      "f3f7",
      "e8d8",
      "f7f8"
    ],
    "rating": 1059,
    "ratingDeviation": 81,
    "popularity": 87,
    "nbPlays": 1723,
    "themes": [
      "attackingF2F7",
      "deflection",
      "mate",
      "mateIn2",
      "opening",
      "short"
    ],
    "gameUrl": "https://lichess.org/y9SWIiaX/black#10",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXsvW",
    "fen": "2r4r/pp3kpp/5p2/2bn4/2P5/1P2PP1B/P6P/1K1R3R w - - 0 20",
    "moves": [
      "h3c8",
      "d5c3",
      "b1b2",
      "c3d1",
      "h1d1",
      "h8c8"
    ],
    "rating": 1245,
    "ratingDeviation": 76,
    "popularity": 94,
    "nbPlays": 1180,
    "themes": [
      "advantage",
      "endgame",
      "fork",
      "long"
    ],
    "gameUrl": "https://lichess.org/ksJxQAMG#39",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "TkRIX",
    "fen": "4r1k1/bpp1qpp1/p2pr2p/PP6/3P4/4PNPP/1Q5K/R3R3 b - - 0 27",
    "moves": [
      "e6e3",
      "e1e3",
      "e7e3",
      "a1e1",
      "e3e1",
      "f3e1"
    ],
    "rating": 1664,
    "ratingDeviation": 77,
    "popularity": 94,
    "nbPlays": 10605,
    "themes": [
      "advantage",
      "clearance",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/JbsYDVEc/black#54",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkQPu",
    "fen": "5rk1/pp4pp/8/8/3nN3/3P3Q/PPP3PP/6K1 w - - 0 28",
    "moves": [
      "e4g5",
      "d4e2",
      "g1h1",
      "f8f1"
    ],
    "rating": 864,
    "ratingDeviation": 77,
    "popularity": 100,
    "nbPlays": 673,
    "themes": [
      "backRankMate",
      "endgame",
      "mate",
      "mateIn2",
      "short"
    ],
    "gameUrl": "https://lichess.org/i8ExpqDq#55",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkRn1",
    "fen": "1N2r1k1/1p3pp1/2p4p/1P6/3PpP1n/4P1qP/2Q3P1/1R3RK1 w - - 0 27",
    "moves": [
      "c2f2",
      "h4f3",
      "f2f3",
      "e4f3"
    ],
    "rating": 1229,
    "ratingDeviation": 74,
    "popularity": 94,
    "nbPlays": 3375,
    "themes": [
      "advantage",
      "kingsideAttack",
      "master",
      "middlegame",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/KB0INFTG#53",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXsaj",
    "fen": "1r2qr2/5k2/1p3b1Q/pPpn1P2/8/3P1R2/1B4PP/R5K1 b - - 0 30",
    "moves": [
      "f6b2",
      "h6g6",
      "f7e7",
      "a1e1"
    ],
    "rating": 1674,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 284,
    "themes": [
      "crushing",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/hH25dm2F/black#60",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "XxuFG",
    "fen": "8/r2k4/P1Rp3p/1K2p1p1/4P3/8/6PP/8 w - - 3 41",
    "moves": [
      "b5b6",
      "a7a6",
      "b6a6",
      "d7c6"
    ],
    "rating": 1085,
    "ratingDeviation": 87,
    "popularity": 93,
    "nbPlays": 583,
    "themes": [
      "crushing",
      "deflection",
      "endgame",
      "rookEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/KD0JlVmH#81",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "XxuG9",
    "fen": "r1b3k1/p4ppp/1qp5/8/2p1PP2/2Nr2P1/PPQB1R2/R5K1 w - - 5 23",
    "moves": [
      "g1g2",
      "c8h3",
      "g2h3",
      "b6f2",
      "c2d3",
      "c4d3"
    ],
    "rating": 1193,
    "ratingDeviation": 80,
    "popularity": 93,
    "nbPlays": 296,
    "themes": [
      "advantage",
      "deflection",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/6gDUA9Jb#45",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "WXqLo",
    "fen": "r3r1k1/pp3pbp/5np1/q3N3/3B2bP/1P1BP3/P1Q2PP1/R3K2R w KQ - 3 17",
    "moves": [
      "c2d2",
      "e8e5",
      "d2a5",
      "e5a5"
    ],
    "rating": 1918,
    "ratingDeviation": 74,
    "popularity": 93,
    "nbPlays": 2253,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/dtriPh2g#33",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXthQ",
    "fen": "rnbqkbnr/1pppp1pp/5p2/8/3P3B/pP2P3/P1P2PPP/RN1QKBNR b KQkq - 1 5",
    "moves": [
      "g7g5",
      "d1h5"
    ],
    "rating": 710,
    "ratingDeviation": 82,
    "popularity": 100,
    "nbPlays": 111,
    "themes": [
      "mate",
      "mateIn1",
      "oneMove",
      "opening"
    ],
    "gameUrl": "https://lichess.org/fJsnl1WW/black#10",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkREJ",
    "fen": "6k1/p5p1/3p3p/1Pp5/8/P4K2/1P6/8 b - - 0 29",
    "moves": [
      "g7g5",
      "a3a4",
      "g8f7",
      "a4a5"
    ],
    "rating": 1590,
    "ratingDeviation": 76,
    "popularity": 86,
    "nbPlays": 197,
    "themes": [
      "crushing",
      "defensiveMove",
      "endgame",
      "pawnEndgame",
      "quietMove",
      "short"
    ],
    "gameUrl": "https://lichess.org/buBxFhhN/black#58",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "Xxu0X",
    "fen": "rn1q1rk1/pbp1bppp/1p2p3/8/3P4/2P2NP1/P1Q1PPBP/R1B2RK1 b - - 0 10",
    "moves": [
      "c7c5",
      "f3g5",
      "e7g5",
      "g2b7"
    ],
    "rating": 1757,
    "ratingDeviation": 82,
    "popularity": 93,
    "nbPlays": 4086,
    "themes": [
      "crushing",
      "discoveredAttack",
      "master",
      "opening",
      "short"
    ],
    "gameUrl": "https://lichess.org/etJ5hc7O/black#20",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXrBa",
    "fen": "8/7p/3Q2pk/2pb1qr1/1p6/3P1P1P/5R2/5R1K b - - 0 41",
    "moves": [
      "f5h3",
      "f2h2",
      "h3h2",
      "h1h2"
    ],
    "rating": 1096,
    "ratingDeviation": 90,
    "popularity": 92,
    "nbPlays": 619,
    "themes": [
      "advantage",
      "endgame",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/yeKwuhPT/black#82",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkTCQ",
    "fen": "r4rk1/pp3p1p/1qp1pbpQ/8/2P5/3B3P/PP1B1P2/1K1R3R w - - 0 20",
    "moves": [
      "b2b3",
      "b6d4",
      "d2c3",
      "d4c3"
    ],
    "rating": 1289,
    "ratingDeviation": 75,
    "popularity": 94,
    "nbPlays": 1727,
    "themes": [
      "crushing",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/y6BvxhGv#39",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxuxS",
    "fen": "8/8/1pR5/1P3Pk1/3KP3/5r1p/8/8 w - - 2 48",
    "moves": [
      "c6b6",
      "h3h2",
      "b6g6",
      "g5h5",
      "g6g8",
      "f3h3"
    ],
    "rating": 1961,
    "ratingDeviation": 75,
    "popularity": 94,
    "nbPlays": 2598,
    "themes": [
      "advancedPawn",
      "crushing",
      "defensiveMove",
      "endgame",
      "long",
      "rookEndgame"
    ],
    "gameUrl": "https://lichess.org/IZTKANDk#95",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXrz4",
    "fen": "r5k1/1p3ppp/2p4q/3p4/r2P2bP/B1PB4/3N1QPK/5R2 b - - 4 24",
    "moves": [
      "a4a3",
      "f2f7",
      "g8h8",
      "f7f8",
      "a8f8",
      "f1f8"
    ],
    "rating": 857,
    "ratingDeviation": 98,
    "popularity": 95,
    "nbPlays": 957,
    "themes": [
      "kingsideAttack",
      "long",
      "mate",
      "mateIn3",
      "middlegame",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/Jg4Fn5hk/black#48",
    "difficulty": "easy",
    "solutionLength": 3
  },
  {
    "id": "WXt3F",
    "fen": "5rk1/2pqbpp1/2n1p2p/1Qpp1b2/3P4/4PNP1/PP1N1PP1/R3K2R w KQ - 1 17",
    "moves": [
      "f3e5",
      "c6e5",
      "b5d7",
      "e5d7"
    ],
    "rating": 1209,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 154,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/bd9F4ez0#33",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "Xxv1l",
    "fen": "3r2k1/4qpp1/p3p2p/P2rPP1P/1p1P4/2p1QP2/6R1/3R2K1 b - - 0 38",
    "moves": [
      "g8h7",
      "g2g7",
      "h7g7",
      "f5f6",
      "e7f6",
      "e5f6"
    ],
    "rating": 2001,
    "ratingDeviation": 74,
    "popularity": 88,
    "nbPlays": 312,
    "themes": [
      "advantage",
      "attraction",
      "endgame",
      "fork",
      "long",
      "master",
      "masterVsMaster",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/iD61gCY7/black#76",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXtAj",
    "fen": "2k1rnr1/p1p5/Ppq1pp2/5n2/2pP1B1p/3Q3P/2PN1PP1/R3R2K w - - 0 26",
    "moves": [
      "d2c4",
      "c6g2"
    ],
    "rating": 1072,
    "ratingDeviation": 78,
    "popularity": 95,
    "nbPlays": 2118,
    "themes": [
      "kingsideAttack",
      "master",
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/BytyEgvT#51",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkR3c",
    "fen": "r1b2r1k/3pqBp1/p2N3p/1pp1P1NQ/1b1p4/8/P4PPP/R4RK1 w - - 0 17",
    "moves": [
      "f7e8",
      "e7g5",
      "d6f7",
      "f8f7",
      "h5g5",
      "h6g5"
    ],
    "rating": 1412,
    "ratingDeviation": 76,
    "popularity": 86,
    "nbPlays": 458,
    "themes": [
      "advantage",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/LOGBUMY2#33",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "WXs9F",
    "fen": "4k1r1/1ppqb3/r7/6Np/pPPpQP1n/6P1/P2BP1K1/R4R2 w - - 0 24",
    "moves": [
      "g3h4",
      "d7g4",
      "g2f2",
      "g4h4",
      "f2f3",
      "h4g4"
    ],
    "rating": 1998,
    "ratingDeviation": 80,
    "popularity": 90,
    "nbPlays": 2994,
    "themes": [
      "advantage",
      "exposedKing",
      "long",
      "master",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/MTZL8YXe#47",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXrg4",
    "fen": "rn2k2r/pQn1ppbp/2p3p1/8/2Pq4/5B1P/PP3PP1/RNB2RK1 b kq - 0 12",
    "moves": [
      "d4b6",
      "b7c8"
    ],
    "rating": 1100,
    "ratingDeviation": 76,
    "popularity": 99,
    "nbPlays": 771,
    "themes": [
      "mate",
      "mateIn1",
      "oneMove",
      "opening"
    ],
    "gameUrl": "https://lichess.org/zqr88ZkI/black#24",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXtUt",
    "fen": "5rk1/5pp1/7p/1N1p4/p2Pn3/3Q2P1/2R2PKP/1q6 b - - 5 34",
    "moves": [
      "f8b8",
      "c2c8",
      "b8c8",
      "d3b1"
    ],
    "rating": 1198,
    "ratingDeviation": 82,
    "popularity": 91,
    "nbPlays": 115,
    "themes": [
      "advantage",
      "discoveredAttack",
      "endgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/1MXySl8B/black#68",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXqsy",
    "fen": "1r1qr1k1/1ppb1p1p/p2p2p1/8/1P1bB3/Q7/P1PP1PPP/RNB2RK1 w - - 0 17",
    "moves": [
      "c2c3",
      "d4f2",
      "f1f2",
      "e8e4",
      "d2d3",
      "e4e1"
    ],
    "rating": 1831,
    "ratingDeviation": 76,
    "popularity": 88,
    "nbPlays": 169,
    "themes": [
      "advantage",
      "kingsideAttack",
      "long",
      "opening"
    ],
    "gameUrl": "https://lichess.org/EGbqujiW#33",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXrnV",
    "fen": "8/6pk/7p/1Q2Nq2/3P2bB/8/5PPP/7K w - - 5 28",
    "moves": [
      "b5c5",
      "f5b1",
      "c5c1",
      "b1c1"
    ],
    "rating": 784,
    "ratingDeviation": 79,
    "popularity": 100,
    "nbPlays": 124,
    "themes": [
      "backRankMate",
      "endgame",
      "mate",
      "mateIn2",
      "short"
    ],
    "gameUrl": "https://lichess.org/UayukowS#55",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXrBw",
    "fen": "7k/1p4p1/p4p1p/4p3/1P1qP3/P1Q2P2/1P4PP/3rR2K w - - 7 41",
    "moves": [
      "c3c8",
      "h8h7",
      "c8c3",
      "d4c3"
    ],
    "rating": 1573,
    "ratingDeviation": 75,
    "popularity": 92,
    "nbPlays": 657,
    "themes": [
      "crushing",
      "endgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/OHU4qMIj#81",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxwyZ",
    "fen": "r4b2/2k2p2/2b1n2q/2p1N3/pp2P3/3P2QB/PPP5/1K3R2 b - - 3 30",
    "moves": [
      "f8d6",
      "f1f7",
      "c7b6",
      "e5c4",
      "b6a6",
      "g3d6"
    ],
    "rating": 2096,
    "ratingDeviation": 78,
    "popularity": 98,
    "nbPlays": 2023,
    "themes": [
      "advantage",
      "discoveredAttack",
      "exposedKing",
      "fork",
      "long",
      "middlegame",
      "pin"
    ],
    "gameUrl": "https://lichess.org/LZUsIzH3/black#60",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXqdY",
    "fen": "5r1k/1pp2Bpp/p6q/3p1Q2/P2P4/2P3bP/1P6/R6K b - - 0 26",
    "moves": [
      "f8f7",
      "f5c8",
      "f7f8",
      "c8f8"
    ],
    "rating": 1004,
    "ratingDeviation": 76,
    "popularity": 100,
    "nbPlays": 1307,
    "themes": [
      "endgame",
      "mate",
      "mateIn2",
      "short"
    ],
    "gameUrl": "https://lichess.org/KKOS2675/black#52",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXqam",
    "fen": "rn3rk1/1p2bppp/5n2/2p1P3/p2P4/4B2P/PqB2QP1/RN3RK1 b - - 0 16",
    "moves": [
      "f6d5",
      "c2h7",
      "g8h7",
      "f2b2"
    ],
    "rating": 1425,
    "ratingDeviation": 75,
    "popularity": 95,
    "nbPlays": 5084,
    "themes": [
      "advantage",
      "discoveredAttack",
      "opening",
      "short"
    ],
    "gameUrl": "https://lichess.org/jfEyd0Df/black#32",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXr4a",
    "fen": "1q4r1/2pk1p1p/2pn2p1/pr1p4/5P2/QP2P3/PBPP2RP/2K3R1 w - - 2 27",
    "moves": [
      "b2e5",
      "d6c4",
      "a3a4",
      "b5b4"
    ],
    "rating": 1694,
    "ratingDeviation": 75,
    "popularity": 92,
    "nbPlays": 1543,
    "themes": [
      "crushing",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/rVpgsPkx#53",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkTgD",
    "fen": "r2r2k1/pp3pbp/2n1bqp1/3p2N1/4p2P/1P1B4/PBPQ1PP1/2KR3R w - - 0 17",
    "moves": [
      "g5e6",
      "f6b2"
    ],
    "rating": 1058,
    "ratingDeviation": 77,
    "popularity": 96,
    "nbPlays": 1595,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove",
      "queensideAttack"
    ],
    "gameUrl": "https://lichess.org/zuQVa2Bh#33",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXsjs",
    "fen": "r3kb1r/p1qnp1pp/2p2p2/1p1n3P/3P2P1/4NP2/PPPB4/R2QKB1R w KQkq - 2 19",
    "moves": [
      "c2c4",
      "c7g3",
      "e1e2",
      "d5f4"
    ],
    "rating": 1175,
    "ratingDeviation": 77,
    "popularity": 96,
    "nbPlays": 1611,
    "themes": [
      "mate",
      "mateIn2",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/LRqVgQVS#37",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXsVO",
    "fen": "6rr/1Ppkqp2/Q2p1n1b/4p3/4P2p/2N2N1P/3P1P2/R1B2RK1 w - - 1 26",
    "moves": [
      "g1h2",
      "h6f4",
      "h2h1",
      "e7e6"
    ],
    "rating": 1612,
    "ratingDeviation": 77,
    "popularity": 93,
    "nbPlays": 4867,
    "themes": [
      "crushing",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/rXZhUH8O#51",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkSls",
    "fen": "r1b1r1k1/pp3ppp/1q1P4/2b1p3/2Pn1P2/3Q2P1/PP2N2P/1B1RK2R b K - 0 19",
    "moves": [
      "e5f4",
      "d3h7",
      "g8f8",
      "h7h8"
    ],
    "rating": 737,
    "ratingDeviation": 113,
    "popularity": 93,
    "nbPlays": 423,
    "themes": [
      "kingsideAttack",
      "mate",
      "mateIn2",
      "opening",
      "short"
    ],
    "gameUrl": "https://lichess.org/okYARE1i/black#38",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXt0R",
    "fen": "r4rk1/1p3pp1/p1pp1q1p/4n3/1P1QP3/PB4RP/2P2PP1/3R2K1 w - - 2 23",
    "moves": [
      "d1f1",
      "e5f3",
      "g3f3",
      "f6d4"
    ],
    "rating": 1178,
    "ratingDeviation": 89,
    "popularity": 91,
    "nbPlays": 535,
    "themes": [
      "crushing",
      "discoveredAttack",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/QlsAHOw7#45",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkRrZ",
    "fen": "5r1k/pb4p1/2q2p1p/1ppN4/4P3/6Q1/1P3PPP/3R2K1 b - - 5 29",
    "moves": [
      "c6e6",
      "d5f4",
      "e6e4",
      "f4g6",
      "h8g8",
      "g6f8"
    ],
    "rating": 1699,
    "ratingDeviation": 74,
    "popularity": 95,
    "nbPlays": 12814,
    "themes": [
      "advantage",
      "endgame",
      "fork",
      "long"
    ],
    "gameUrl": "https://lichess.org/jpwkdI7L/black#58",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkQzW",
    "fen": "6R1/5R2/8/4rPkp/6r1/5K2/8/8 b - - 8 54",
    "moves": [
      "g5h4",
      "g8g4",
      "h5g4",
      "f3f4"
    ],
    "rating": 822,
    "ratingDeviation": 80,
    "popularity": 100,
    "nbPlays": 282,
    "themes": [
      "crushing",
      "endgame",
      "rookEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/fy8Zd72w/black#108",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXtlw",
    "fen": "1qr3k1/2p2ppp/2Qbpn2/1N6/8/6P1/1P2PP1P/R1B3K1 b - - 2 19",
    "moves": [
      "b8b6",
      "c6b6",
      "c7b6",
      "b5d6"
    ],
    "rating": 1418,
    "ratingDeviation": 78,
    "popularity": 94,
    "nbPlays": 800,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/tZpHi1Sr/black#38",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXrXR",
    "fen": "r1b1k2r/p4p2/2p1pq1p/3p2p1/8/1B1Q2B1/P1P2PPP/4R1K1 b kq - 0 16",
    "moves": [
      "f6g6",
      "d3c3",
      "e8g8",
      "c3c6",
      "c8b7",
      "c6b7"
    ],
    "rating": 2097,
    "ratingDeviation": 77,
    "popularity": 91,
    "nbPlays": 603,
    "themes": [
      "advantage",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/KS6Z6jzv/black#32",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXtXf",
    "fen": "1Q6/7k/P6p/2Q5/5b1P/5b2/3p1P2/6K1 w - - 0 52",
    "moves": [
      "b8f4",
      "d2d1q",
      "g1h2",
      "d1h1",
      "h2g3",
      "h1g2"
    ],
    "rating": 892,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 427,
    "themes": [
      "advancedPawn",
      "endgame",
      "long",
      "mate",
      "mateIn3",
      "promotion"
    ],
    "gameUrl": "https://lichess.org/tSEuizdj#103",
    "difficulty": "easy",
    "solutionLength": 3
  },
  {
    "id": "TkSdA",
    "fen": "6k1/6pp/4p3/1pB1Pp1P/2pP4/5bP1/1r1b1P2/R2N2K1 b - - 3 36",
    "moves": [
      "f3d1",
      "a1a8",
      "g8f7",
      "a8f8"
    ],
    "rating": 1118,
    "ratingDeviation": 78,
    "popularity": 90,
    "nbPlays": 2220,
    "themes": [
      "endgame",
      "mate",
      "mateIn2",
      "operaMate",
      "short"
    ],
    "gameUrl": "https://lichess.org/rIcSzDCb/black#72",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "Xxx1V",
    "fen": "r6r/1p3p2/p1kNb1p1/2P5/PP5p/8/2P4P/2KRR3 b - - 0 24",
    "moves": [
      "h4h3",
      "d6f7",
      "e6f7",
      "d1d6",
      "c6c7",
      "e1e7"
    ],
    "rating": 2045,
    "ratingDeviation": 80,
    "popularity": 92,
    "nbPlays": 1034,
    "themes": [
      "clearance",
      "crushing",
      "endgame",
      "exposedKing",
      "long",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/GiIMgTae/black#48",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkSvg",
    "fen": "4Q3/2p2ppk/pb3q1p/1p1rp3/8/1B5P/PP3PP1/4R1K1 w - - 1 24",
    "moves": [
      "b3d5",
      "f6f2",
      "g1h2",
      "f2e1",
      "d5e4",
      "e1e4"
    ],
    "rating": 993,
    "ratingDeviation": 77,
    "popularity": 96,
    "nbPlays": 5140,
    "themes": [
      "crushing",
      "endgame",
      "fork",
      "long"
    ],
    "gameUrl": "https://lichess.org/CXuwO00i#47",
    "difficulty": "easy",
    "solutionLength": 3
  },
  {
    "id": "WXsxa",
    "fen": "2k1r3/1pp3pp/r3bp2/p1nNp3/1nP1P3/5N1P/PP3PP1/1BKR3R w - - 3 18",
    "moves": [
      "a2a3",
      "c5b3"
    ],
    "rating": 1492,
    "ratingDeviation": 82,
    "popularity": 88,
    "nbPlays": 422,
    "themes": [
      "master",
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/LjzJN9Uh#35",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "TkTmu",
    "fen": "r4rk1/pbq4p/1p2QPn1/2p3P1/P2p3P/3P4/1PP3B1/R4RK1 b - - 0 26",
    "moves": [
      "g8h8",
      "f6f7",
      "c7e5",
      "e6e5",
      "g6e5",
      "g2b7"
    ],
    "rating": 1906,
    "ratingDeviation": 78,
    "popularity": 91,
    "nbPlays": 1279,
    "themes": [
      "advancedPawn",
      "crushing",
      "long",
      "master",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/YRzupex0/black#52",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkR5M",
    "fen": "7r/pp2k1b1/4p1P1/3pP2K/3P1BR1/2P5/PP6/8 w - - 1 38",
    "moves": [
      "h5g5",
      "g7h6",
      "g5h4",
      "h6f4"
    ],
    "rating": 1064,
    "ratingDeviation": 85,
    "popularity": 96,
    "nbPlays": 2694,
    "themes": [
      "deflection",
      "discoveredAttack",
      "discoveredCheck",
      "endgame",
      "mate",
      "mateIn2",
      "pillsburysMate",
      "short"
    ],
    "gameUrl": "https://lichess.org/rhzjvJLB#75",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkTpA",
    "fen": "r6r/ppp1k3/2p4p/8/5p2/2N1bPPb/PPP1B2P/1K1RR3 b - - 2 19",
    "moves": [
      "e3f2",
      "e2f1",
      "f2e1",
      "d1e1"
    ],
    "rating": 1597,
    "ratingDeviation": 77,
    "popularity": 88,
    "nbPlays": 2048,
    "themes": [
      "advantage",
      "discoveredAttack",
      "discoveredCheck",
      "middlegame",
      "sacrifice",
      "short"
    ],
    "gameUrl": "https://lichess.org/0ccelY6I/black#38",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxxB5",
    "fen": "r2q2k1/pp3rpp/3pR3/3Q4/8/2P5/PP3bKP/R1B5 b - - 1 20",
    "moves": [
      "d8h4",
      "e6e4",
      "h4e4",
      "d5e4"
    ],
    "rating": 2051,
    "ratingDeviation": 78,
    "popularity": 91,
    "nbPlays": 248,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/F3m0BRHa/black#40",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkSCW",
    "fen": "8/b6p/Pr1kpp2/R2p4/3N4/3K3P/5PP1/8 b - - 5 37",
    "moves": [
      "b6b2",
      "d4b5",
      "b2b5",
      "a5b5"
    ],
    "rating": 847,
    "ratingDeviation": 76,
    "popularity": 100,
    "nbPlays": 442,
    "themes": [
      "crushing",
      "endgame",
      "fork",
      "short"
    ],
    "gameUrl": "https://lichess.org/OwbTYBBf/black#74",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkSYf",
    "fen": "r1bq1rk1/ppp2ppp/8/8/2B3n1/2Q5/PPPN1PPK/R1B2R2 w - - 1 14",
    "moves": [
      "h2h1",
      "d8h4",
      "c3h3",
      "g4f2",
      "f1f2",
      "c8h3"
    ],
    "rating": 1581,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 976,
    "themes": [
      "advantage",
      "discoveredAttack",
      "fork",
      "long",
      "opening"
    ],
    "gameUrl": "https://lichess.org/Rg7348px#27",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "XxwUc",
    "fen": "r5k1/5p1p/4b1pq/2Q5/4P3/1P3P1P/P5P1/3R1K2 b - - 0 42",
    "moves": [
      "a8a2",
      "d1d8",
      "g8g7",
      "c5f8"
    ],
    "rating": 1980,
    "ratingDeviation": 78,
    "popularity": 91,
    "nbPlays": 1149,
    "themes": [
      "crushing",
      "endgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/bKRiC3ax/black#84",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXrNN",
    "fen": "4Q3/ppb1Nppk/5q1p/2pb4/8/1P3P2/P1B3PP/6K1 b - - 3 28",
    "moves": [
      "g7g6",
      "e8g8"
    ],
    "rating": 884,
    "ratingDeviation": 82,
    "popularity": 96,
    "nbPlays": 770,
    "themes": [
      "endgame",
      "master",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/ytpxZoa7/black#56",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXq94",
    "fen": "2kr3r/ppp1qppp/2nb1n2/8/8/2N1PB2/PPP2PPP/R1BQ1RK1 w - - 3 10",
    "moves": [
      "f3c6",
      "d6h2",
      "g1h2",
      "d8d1"
    ],
    "rating": 1196,
    "ratingDeviation": 77,
    "popularity": 89,
    "nbPlays": 2512,
    "themes": [
      "advantage",
      "discoveredAttack",
      "kingsideAttack",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/axBSxRVm#19",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkQTA",
    "fen": "r1b2rk1/p2n1ppp/4q3/b4N2/2P2RQ1/P5B1/6PP/R6K b - - 3 24",
    "moves": [
      "g7g6",
      "f5h6",
      "g8g7",
      "f4f7",
      "e6f7",
      "h6f7"
    ],
    "rating": 1653,
    "ratingDeviation": 75,
    "popularity": 88,
    "nbPlays": 119,
    "themes": [
      "advantage",
      "discoveredAttack",
      "kingsideAttack",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/EWxxoDSA/black#48",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXq6f",
    "fen": "2r2rk1/p5pp/2pb4/3pPp2/Q4B2/2P2P1n/PP4PP/R4RqK w - - 7 21",
    "moves": [
      "f1g1",
      "h3f2"
    ],
    "rating": 936,
    "ratingDeviation": 87,
    "popularity": 96,
    "nbPlays": 201,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove",
      "smotheredMate"
    ],
    "gameUrl": "https://lichess.org/yWHKHz4t#41",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXqeO",
    "fen": "8/8/8/1Ppk2p1/6P1/2K5/8/8 b - - 0 56",
    "moves": [
      "c5c4",
      "b5b6",
      "d5c6",
      "c3c4"
    ],
    "rating": 1111,
    "ratingDeviation": 76,
    "popularity": 95,
    "nbPlays": 422,
    "themes": [
      "crushing",
      "endgame",
      "pawnEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/DPg0IgQV/black#112",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkTh3",
    "fen": "6rk/p5qp/1bp5/3pP3/3P4/1P5R/P4Q1P/2B4K b - - 3 33",
    "moves": [
      "g7e5",
      "h3h7",
      "h8h7",
      "f2h4",
      "h7g6",
      "d4e5"
    ],
    "rating": 1964,
    "ratingDeviation": 76,
    "popularity": 95,
    "nbPlays": 2977,
    "themes": [
      "attraction",
      "crushing",
      "endgame",
      "long",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/aqW71x5M/black#66",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkR82",
    "fen": "8/4p1k1/3p4/4n1pp/8/3n2PP/1Q3P1K/8 w - - 1 56",
    "moves": [
      "b2d2",
      "e5f3",
      "h2h1",
      "f3d2"
    ],
    "rating": 802,
    "ratingDeviation": 94,
    "popularity": 96,
    "nbPlays": 667,
    "themes": [
      "crushing",
      "endgame",
      "fork",
      "master",
      "short"
    ],
    "gameUrl": "https://lichess.org/ooRhmzq9#111",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "Xxu5W",
    "fen": "r2qrn1k/1b3pp1/pp1p4/2pP1BN1/1PPb1P2/P2Q4/6PP/2B2R1K b - - 6 19",
    "moves": [
      "b7c8",
      "g5f7",
      "h8g8",
      "f7d8",
      "c8f5",
      "d3f5"
    ],
    "rating": 1361,
    "ratingDeviation": 78,
    "popularity": 95,
    "nbPlays": 15422,
    "themes": [
      "advantage",
      "fork",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/7J0jvAS3/black#38",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "XxxDL",
    "fen": "8/1P6/2K5/8/1r4k1/8/7p/4R3 b - - 6 61",
    "moves": [
      "b4c4",
      "c6b5",
      "c4c2",
      "e1b1",
      "h2h1q",
      "b1h1"
    ],
    "rating": 2015,
    "ratingDeviation": 79,
    "popularity": 92,
    "nbPlays": 3331,
    "themes": [
      "crushing",
      "defensiveMove",
      "endgame",
      "long",
      "quietMove",
      "rookEndgame"
    ],
    "gameUrl": "https://lichess.org/7jIFtz18/black#122",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "Xxuvp",
    "fen": "4Qbk1/p4p1p/1p1Bp1p1/8/3PB3/4P2P/P3nPP1/4q2K w - - 1 30",
    "moves": [
      "h1h2",
      "e1g1"
    ],
    "rating": 816,
    "ratingDeviation": 97,
    "popularity": 96,
    "nbPlays": 146,
    "themes": [
      "endgame",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/BvsagE7q#59",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkRoU",
    "fen": "r1bqr2N/b4kp1/p1pp3p/1p5Q/1P2P3/P2P3P/1Bn2PP1/5K1R b - - 1 19",
    "moves": [
      "f7e7",
      "h5f7"
    ],
    "rating": 1287,
    "ratingDeviation": 76,
    "popularity": 95,
    "nbPlays": 16634,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/UGE0vHSc/black#38",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "WXsZt",
    "fen": "8/8/7p/6p1/4Q1kq/8/4KP2/8 b - - 3 56",
    "moves": [
      "g4h3",
      "e4h1",
      "h3g4",
      "h1f3"
    ],
    "rating": 2012,
    "ratingDeviation": 76,
    "popularity": 100,
    "nbPlays": 699,
    "themes": [
      "endgame",
      "mate",
      "mateIn2",
      "queenEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/ibLMUFCM/black#112",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkSQx",
    "fen": "6k1/1R3pp1/4p3/2Np4/3P1b2/2rB4/8/5K2 b - - 0 37",
    "moves": [
      "f4e3",
      "b7b8"
    ],
    "rating": 882,
    "ratingDeviation": 79,
    "popularity": 85,
    "nbPlays": 456,
    "themes": [
      "endgame",
      "master",
      "mate",
      "mateIn1",
      "oneMove",
      "pillsburysMate"
    ],
    "gameUrl": "https://lichess.org/aYXBv4Np/black#74",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkRmC",
    "fen": "7r/pp1r2kp/7p/5R2/3n4/1B6/PPP2PPP/2KR4 w - - 3 24",
    "moves": [
      "f5f4",
      "d4e2",
      "c1b1",
      "d7d1"
    ],
    "rating": 1466,
    "ratingDeviation": 74,
    "popularity": 98,
    "nbPlays": 1845,
    "themes": [
      "backRankMate",
      "deflection",
      "discoveredAttack",
      "endgame",
      "fork",
      "mate",
      "mateIn2",
      "short"
    ],
    "gameUrl": "https://lichess.org/RT47X6db#47",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkTIi",
    "fen": "6k1/6p1/p2Pp1Q1/b6p/p6P/r1q2rB1/6P1/1R1R3K w - - 0 39",
    "moves": [
      "g2f3",
      "c3f3",
      "h1g1",
      "a5b6",
      "b1b6",
      "f3d1"
    ],
    "rating": 1965,
    "ratingDeviation": 75,
    "popularity": 90,
    "nbPlays": 337,
    "themes": [
      "crushing",
      "deflection",
      "exposedKing",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/3Bu4j7wL#77",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXrkU",
    "fen": "2k4r/p2q4/Pp3Q2/1p1p4/1BnP4/7b/2P2PK1/R3R3 w - - 1 31",
    "moves": [
      "g2g3",
      "d7g4",
      "g3h2",
      "g4g2"
    ],
    "rating": 1031,
    "ratingDeviation": 78,
    "popularity": 86,
    "nbPlays": 215,
    "themes": [
      "mate",
      "mateIn2",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/hJiIs8CS#61",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkSiv",
    "fen": "7k/5nb1/R2n2pp/8/1B1p1P2/6P1/4K2P/8 b - - 2 35",
    "moves": [
      "d6e8",
      "a6a8",
      "h8h7",
      "a8e8"
    ],
    "rating": 1309,
    "ratingDeviation": 75,
    "popularity": 93,
    "nbPlays": 844,
    "themes": [
      "advantage",
      "endgame",
      "master",
      "masterVsMaster",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/wE69Rl3M/black#70",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxwuB",
    "fen": "4K3/1P6/8/8/8/5Q2/3q2p1/6k1 b - - 11 82",
    "moves": [
      "d2a2",
      "b7b8q",
      "a2g8",
      "f3f8",
      "g8f8",
      "e8f8"
    ],
    "rating": 1723,
    "ratingDeviation": 81,
    "popularity": 90,
    "nbPlays": 2515,
    "themes": [
      "advancedPawn",
      "crushing",
      "defensiveMove",
      "endgame",
      "long",
      "promotion",
      "queenEndgame"
    ],
    "gameUrl": "https://lichess.org/eMA0th1u/black#164",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXpsC",
    "fen": "r4rk1/pp5p/2p2np1/3p4/3P4/2P1qBQ1/PP2N1K1/R2R4 w - - 3 27",
    "moves": [
      "f3d5",
      "f6d5",
      "g3e3",
      "d5e3"
    ],
    "rating": 1084,
    "ratingDeviation": 84,
    "popularity": 93,
    "nbPlays": 2073,
    "themes": [
      "crushing",
      "hangingPiece",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/PKOvME5m#53",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXrQm",
    "fen": "8/8/6p1/4p2k/r5P1/PR6/5KP1/8 b - - 0 37",
    "moves": [
      "h5g4",
      "b3b4",
      "a4b4",
      "a3b4"
    ],
    "rating": 1487,
    "ratingDeviation": 78,
    "popularity": 93,
    "nbPlays": 4335,
    "themes": [
      "crushing",
      "endgame",
      "rookEndgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/eX2DuUMR/black#74",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkTrO",
    "fen": "6r1/6P1/3R4/8/4p3/1pk3KP/3n4/3B4 w - - 3 46",
    "moves": [
      "d6d7",
      "b3b2",
      "d7c7",
      "d2c4"
    ],
    "rating": 1858,
    "ratingDeviation": 75,
    "popularity": 90,
    "nbPlays": 1794,
    "themes": [
      "advancedPawn",
      "crushing",
      "defensiveMove",
      "endgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/40lLiha5#91",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "WXq6q",
    "fen": "rnb1k1nr/pppp1ppp/5q2/2b1p3/4P3/2N5/PPPP1PPP/R1BQKBNR w KQkq - 3 4",
    "moves": [
      "b2b3",
      "f6f2"
    ],
    "rating": 967,
    "ratingDeviation": 77,
    "popularity": 85,
    "nbPlays": 437,
    "themes": [
      "attackingF2F7",
      "master",
      "mate",
      "mateIn1",
      "oneMove",
      "opening"
    ],
    "gameUrl": "https://lichess.org/hiVUaU02#7",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkQt7",
    "fen": "3r2k1/1b1r1pbp/p3p1p1/1p2P3/1n6/1P3NQ1/1Rp1BPPP/2R3K1 w - - 2 25",
    "moves": [
      "h2h3",
      "d7d1",
      "e2d1",
      "d8d1",
      "g1h2",
      "d1c1"
    ],
    "rating": 1387,
    "ratingDeviation": 78,
    "popularity": 95,
    "nbPlays": 23883,
    "themes": [
      "crushing",
      "long",
      "middlegame",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/68RF3JtA#49",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "Xxx99",
    "fen": "r4r1k/ppp1b1p1/6q1/4p1B1/3nP1Q1/3P4/PPP2PPP/RNR3K1 w - - 3 16",
    "moves": [
      "g4h4",
      "h8g8",
      "g5e7",
      "d4f3",
      "g1h1",
      "f3h4"
    ],
    "rating": 1932,
    "ratingDeviation": 75,
    "popularity": 93,
    "nbPlays": 1397,
    "themes": [
      "advantage",
      "defensiveMove",
      "long",
      "middlegame",
      "pin",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/Vp4VnAGV#31",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "XxvL7",
    "fen": "k3r3/1p6/1q1n4/p2P4/7Q/P1R4P/4N3/4K3 b - - 0 42",
    "moves": [
      "e8e2",
      "e1e2",
      "b6b2",
      "e2d3"
    ],
    "rating": 1002,
    "ratingDeviation": 87,
    "popularity": 95,
    "nbPlays": 121,
    "themes": [
      "advantage",
      "defensiveMove",
      "endgame",
      "hangingPiece",
      "short"
    ],
    "gameUrl": "https://lichess.org/Tu7wO375/black#84",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXqV8",
    "fen": "8/5pkp/5np1/4QP2/3PB3/P1P5/1P6/1K3q2 w - - 3 51",
    "moves": [
      "b1c2",
      "f1e2",
      "c2b3",
      "e2e4"
    ],
    "rating": 1376,
    "ratingDeviation": 74,
    "popularity": 95,
    "nbPlays": 23179,
    "themes": [
      "advantage",
      "endgame",
      "short"
    ],
    "gameUrl": "https://lichess.org/u1qzms26#101",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "WXrEZ",
    "fen": "2q3k1/5rp1/7p/n1bQp3/1P6/2P2p2/P2P1PPP/R1B2RK1 w - - 0 20",
    "moves": [
      "b4c5",
      "c8g4",
      "d5f3",
      "f7f3"
    ],
    "rating": 1635,
    "ratingDeviation": 74,
    "popularity": 94,
    "nbPlays": 8107,
    "themes": [
      "advantage",
      "middlegame",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/vLBb3ftS#39",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkTwB",
    "fen": "1k6/1P5R/1r1Kp3/4P2p/8/8/4P3/8 w - - 4 51",
    "moves": [
      "d6e7",
      "b6b7",
      "e7e6",
      "b7h7"
    ],
    "rating": 837,
    "ratingDeviation": 95,
    "popularity": 93,
    "nbPlays": 439,
    "themes": [
      "crushing",
      "endgame",
      "master",
      "rookEndgame",
      "short",
      "skewer"
    ],
    "gameUrl": "https://lichess.org/hbMp1gb7#101",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkSPk",
    "fen": "8/8/3B4/8/1P2N1k1/5p2/1r1K4/8 w - - 8 62",
    "moves": [
      "d2e3",
      "b2e2",
      "e3d4",
      "e2e4",
      "d4e4",
      "f3f2"
    ],
    "rating": 1501,
    "ratingDeviation": 78,
    "popularity": 100,
    "nbPlays": 109,
    "themes": [
      "advancedPawn",
      "crushing",
      "endgame",
      "exposedKing",
      "long",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/uZX9mgpJ#123",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "WXq6a",
    "fen": "2r3k1/5p2/6p1/p4q1p/1p1Q4/1P3N1P/P2R1PP1/6K1 w - - 1 37",
    "moves": [
      "d4b6",
      "c8c1",
      "g1h2",
      "f5f4",
      "g2g3",
      "f4f3"
    ],
    "rating": 1712,
    "ratingDeviation": 75,
    "popularity": 93,
    "nbPlays": 490,
    "themes": [
      "crushing",
      "deflection",
      "endgame",
      "long"
    ],
    "gameUrl": "https://lichess.org/hahHHPFy#73",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXsX0",
    "fen": "8/6k1/pp5p/1NpB2p1/2P3Pn/1P1P2KP/Pb6/8 w - - 0 41",
    "moves": [
      "b5c7",
      "b2e5",
      "g3f2",
      "e5c7"
    ],
    "rating": 937,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 293,
    "themes": [
      "advantage",
      "endgame",
      "fork",
      "short"
    ],
    "gameUrl": "https://lichess.org/AwWohnSG#81",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkRjo",
    "fen": "b1r2r2/7k/p2Np1p1/1p1n3p/2pP3q/P1P5/1PQ2PPP/1Bb1R1K1 b - - 1 28",
    "moves": [
      "c1f4",
      "c2g6",
      "h7h8",
      "g6h7"
    ],
    "rating": 1337,
    "ratingDeviation": 77,
    "popularity": 98,
    "nbPlays": 1874,
    "themes": [
      "mate",
      "mateIn2",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/yLidxmk0/black#56",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "XxwOY",
    "fen": "1r3r2/p2bpp2/2pp4/2q4k/4P3/1P3P1p/P1P1Q3/2KR3R b - - 2 25",
    "moves": [
      "c5g5",
      "f3f4",
      "d7g4",
      "h1h3"
    ],
    "rating": 1758,
    "ratingDeviation": 75,
    "popularity": 96,
    "nbPlays": 3221,
    "themes": [
      "advantage",
      "discoveredAttack",
      "discoveredCheck",
      "middlegame",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/H3zidZVY/black#50",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "TkS9O",
    "fen": "3R4/pp3pk1/1qp1pNpp/2n1P3/2P2P2/1P1Q3P/P5PK/8 b - - 0 30",
    "moves": [
      "c5d3",
      "d8g8"
    ],
    "rating": 700,
    "ratingDeviation": 97,
    "popularity": 96,
    "nbPlays": 349,
    "themes": [
      "endgame",
      "hookMate",
      "master",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/JAmgj9sw/black#60",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "TkSoU",
    "fen": "5rk1/pbp2p2/6r1/8/5p1Q/3Pbq2/PPP3PP/R2N1R1K w - - 0 23",
    "moves": [
      "g2f3",
      "b7f3",
      "f1f3",
      "g6g1"
    ],
    "rating": 1285,
    "ratingDeviation": 76,
    "popularity": 97,
    "nbPlays": 736,
    "themes": [
      "kingsideAttack",
      "mate",
      "mateIn2",
      "middlegame",
      "operaMate",
      "sacrifice",
      "short"
    ],
    "gameUrl": "https://lichess.org/DhRxiPZV#45",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkR0c",
    "fen": "6rk/p7/1p6/1b2PQ2/8/P7/6rP/4R2K w - - 0 41",
    "moves": [
      "e5e6",
      "g2g1",
      "e1g1",
      "b5c6",
      "g1g2",
      "c6g2"
    ],
    "rating": 1804,
    "ratingDeviation": 76,
    "popularity": 94,
    "nbPlays": 13268,
    "themes": [
      "crushing",
      "endgame",
      "long",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/PpljGfSy#81",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkSxc",
    "fen": "4Rrk1/1ppr1pp1/p1n4Q/5q1p/3P2N1/P1P4P/1P3PP1/4R1K1 b - - 3 21",
    "moves": [
      "h5g4",
      "e8f8",
      "g8f8",
      "h6h8"
    ],
    "rating": 951,
    "ratingDeviation": 76,
    "popularity": 90,
    "nbPlays": 251,
    "themes": [
      "attraction",
      "kingsideAttack",
      "mate",
      "mateIn2",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/VU75lXdV/black#42",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "WXsMo",
    "fen": "5rk1/pb3ppp/4pn2/1B6/1P1q1P2/P3N1P1/4QP1P/2R3K1 w - - 0 23",
    "moves": [
      "e2d1",
      "d4e4",
      "b5c6",
      "b7c6",
      "c1c6",
      "e4c6"
    ],
    "rating": 1441,
    "ratingDeviation": 75,
    "popularity": 90,
    "nbPlays": 1333,
    "themes": [
      "advantage",
      "long",
      "middlegame"
    ],
    "gameUrl": "https://lichess.org/0jT1O64D#45",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "XxvUe",
    "fen": "1r3r1k/2p1q2p/5bp1/p3p3/P3R3/2P2N2/1PQ3PP/4R1K1 w - - 4 24",
    "moves": [
      "f3e5",
      "e7c5",
      "e1e3",
      "f6g5"
    ],
    "rating": 2059,
    "ratingDeviation": 77,
    "popularity": 90,
    "nbPlays": 667,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/PXflDGEg#47",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "Xxuau",
    "fen": "8/1p6/1bpk1p2/4pQ1p/4P3/2P3P1/P2r1P2/6K1 w - - 2 37",
    "moves": [
      "g1g2",
      "d2f2",
      "f5f2",
      "b6f2"
    ],
    "rating": 718,
    "ratingDeviation": 82,
    "popularity": 100,
    "nbPlays": 581,
    "themes": [
      "crushing",
      "endgame",
      "fork",
      "master",
      "short"
    ],
    "gameUrl": "https://lichess.org/KFJ4IN8v#73",
    "difficulty": "easy",
    "solutionLength": 2
  },
  {
    "id": "TkR6W",
    "fen": "r1b1kb1r/ppq2pp1/2p2n2/4n2p/4P3/2NB1N2/PP1B1PPP/2RQK2R w Kkq - 0 11",
    "moves": [
      "d2f4",
      "e5d3",
      "d1d3",
      "c7f4"
    ],
    "rating": 1397,
    "ratingDeviation": 79,
    "popularity": 93,
    "nbPlays": 2121,
    "themes": [
      "crushing",
      "discoveredAttack",
      "opening",
      "short"
    ],
    "gameUrl": "https://lichess.org/sqtiIvJk#21",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkSdn",
    "fen": "6k1/2q2pp1/2P4p/4P3/5P2/2Q3P1/p5BP/6K1 w - - 0 36",
    "moves": [
      "g2d5",
      "c7a7",
      "g1g2",
      "a2a1q",
      "c3a1",
      "a7a1"
    ],
    "rating": 1978,
    "ratingDeviation": 74,
    "popularity": 100,
    "nbPlays": 151,
    "themes": [
      "advancedPawn",
      "advantage",
      "endgame",
      "long",
      "promotion"
    ],
    "gameUrl": "https://lichess.org/MhEoLBcF#71",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXqY8",
    "fen": "4r3/6pk/2p5/4N2p/1B1n1K2/3B4/PP6/8 b - - 3 44",
    "moves": [
      "h7h6",
      "e5f7"
    ],
    "rating": 921,
    "ratingDeviation": 98,
    "popularity": 96,
    "nbPlays": 282,
    "themes": [
      "endgame",
      "master",
      "masterVsMaster",
      "mate",
      "mateIn1",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/9xs364kw/black#88",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXqtq",
    "fen": "r1bq1rk1/ppp1bp1p/2p3p1/4N2Q/3n4/1P1P4/PBPN1PPP/2R1R1K1 w - - 0 14",
    "moves": [
      "h5h6",
      "e7g5",
      "h6g5",
      "d8g5"
    ],
    "rating": 1367,
    "ratingDeviation": 76,
    "popularity": 93,
    "nbPlays": 2256,
    "themes": [
      "crushing",
      "middlegame",
      "short",
      "trappedPiece"
    ],
    "gameUrl": "https://lichess.org/tTHghtdY#27",
    "difficulty": "medium",
    "solutionLength": 2
  },
  {
    "id": "TkR6G",
    "fen": "r2qk1nr/1p2b3/p3p3/1p1b1p2/3P1B1p/2N5/PPP1QPPP/2KRR3 b kq - 1 16",
    "moves": [
      "e7g5",
      "c3d5",
      "d8d5",
      "f4g5"
    ],
    "rating": 1765,
    "ratingDeviation": 76,
    "popularity": 91,
    "nbPlays": 139,
    "themes": [
      "advantage",
      "middlegame",
      "pin",
      "short"
    ],
    "gameUrl": "https://lichess.org/xHaiGldN/black#32",
    "difficulty": "hard",
    "solutionLength": 2
  },
  {
    "id": "Xxuwg",
    "fen": "3r2kr/1p3pp1/p7/2p3P1/P5b1/3P4/1PPBn1PK/R3QR2 w - - 1 22",
    "moves": [
      "e1h4",
      "h8h4"
    ],
    "rating": 837,
    "ratingDeviation": 84,
    "popularity": 89,
    "nbPlays": 391,
    "themes": [
      "anastasiaMate",
      "hangingPiece",
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/eXxYUNT9#43",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "XxuTj",
    "fen": "r5k1/1p4p1/p1pp3p/3Pp1q1/2P5/4Q1Pn/PP1N1rKP/R3R3 w - - 0 23",
    "moves": [
      "g2h3",
      "g5h5"
    ],
    "rating": 1189,
    "ratingDeviation": 78,
    "popularity": 89,
    "nbPlays": 499,
    "themes": [
      "mate",
      "mateIn1",
      "middlegame",
      "oneMove"
    ],
    "gameUrl": "https://lichess.org/ayWZ4RFE#45",
    "difficulty": "medium",
    "solutionLength": 1
  },
  {
    "id": "TkSnF",
    "fen": "6k1/1pp4p/p3RBp1/5q2/PP6/6Q1/6PK/3r4 w - - 0 30",
    "moves": [
      "g3b3",
      "f5f4",
      "b3g3",
      "d1h1",
      "h2h1",
      "f4g3"
    ],
    "rating": 1951,
    "ratingDeviation": 77,
    "popularity": 91,
    "nbPlays": 1303,
    "themes": [
      "crushing",
      "deflection",
      "endgame",
      "long"
    ],
    "gameUrl": "https://lichess.org/BjeeVhYl#59",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "WXsLW",
    "fen": "5rQk/1p4pp/p1p4N/2P5/1P6/3P3P/1q3PPK/8 b - - 7 40",
    "moves": [
      "f8g8",
      "h6f7"
    ],
    "rating": 799,
    "ratingDeviation": 94,
    "popularity": 96,
    "nbPlays": 377,
    "themes": [
      "endgame",
      "mate",
      "mateIn1",
      "oneMove",
      "smotheredMate"
    ],
    "gameUrl": "https://lichess.org/E2nG5cH9/black#80",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXtGG",
    "fen": "1k3b1r/pp3pp1/q2p1n2/P6p/8/2Q2PBP/1P2rP2/R1R3K1 b - - 3 19",
    "moves": [
      "f8e7",
      "c3c7",
      "b8a8",
      "c7c8",
      "h8c8",
      "c1c8"
    ],
    "rating": 1206,
    "ratingDeviation": 75,
    "popularity": 100,
    "nbPlays": 534,
    "themes": [
      "backRankMate",
      "long",
      "mate",
      "mateIn3",
      "middlegame",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/5DVbII9C/black#38",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "TkRr2",
    "fen": "r1bq1rk1/pppp1ppp/2nb1n2/6B1/4P3/3P1N2/PPP1B1PP/RN1QK2R b KQ - 6 7",
    "moves": [
      "c6e5",
      "f3e5",
      "d6e5",
      "d3d4",
      "e5d6",
      "e4e5"
    ],
    "rating": 1751,
    "ratingDeviation": 76,
    "popularity": 93,
    "nbPlays": 2823,
    "themes": [
      "crushing",
      "long",
      "opening"
    ],
    "gameUrl": "https://lichess.org/WkKMjcoy/black#14",
    "difficulty": "hard",
    "solutionLength": 3
  },
  {
    "id": "TkRXt",
    "fen": "r1bq1knr/pppnp1b1/3p2Q1/6N1/2PP1p2/2N4P/PP2PPP1/R3KB1R b KQ - 0 11",
    "moves": [
      "d8e8",
      "g5e6"
    ],
    "rating": 1046,
    "ratingDeviation": 77,
    "popularity": 97,
    "nbPlays": 432,
    "themes": [
      "mate",
      "mateIn1",
      "oneMove",
      "opening"
    ],
    "gameUrl": "https://lichess.org/qZirdLr6/black#22",
    "difficulty": "easy",
    "solutionLength": 1
  },
  {
    "id": "WXsRy",
    "fen": "2r1q2k/pQP4p/6p1/8/8/2P4P/PP4P1/3Rb1K1 b - - 2 27",
    "moves": [
      "e1g3",
      "b7c8",
      "e8c8",
      "d1d8",
      "h8g7",
      "d8c8"
    ],
    "rating": 1534,
    "ratingDeviation": 76,
    "popularity": 90,
    "nbPlays": 680,
    "themes": [
      "attraction",
      "crushing",
      "endgame",
      "fork",
      "long",
      "sacrifice"
    ],
    "gameUrl": "https://lichess.org/cUHVUr9F/black#54",
    "difficulty": "medium",
    "solutionLength": 3
  },
  {
    "id": "WXrux",
    "fen": "r4rk1/2qbbpp1/p6B/1p6/2BP4/2PQ4/P4PP1/R4K1R w - - 0 24",
    "moves": [
      "h6f4",
      "c7c4",
      "d3c4",
      "b5c4"
    ],
    "rating": 1793,
    "ratingDeviation": 78,
    "popularity": 96,
    "nbPlays": 22257,
    "themes": [
      "advantage",
      "middlegame",
      "short"
    ],
    "gameUrl": "https://lichess.org/Mu6m6WXf#47",
    "difficulty": "hard",
    "solutionLength": 2
  }
];
